<?php
$printo_slider_sc = printo_get_theme_option( 'front_page_title_shortcode' );
if ( ! empty( $printo_slider_sc ) && strpos( $printo_slider_sc, '[' ) !== false && strpos( $printo_slider_sc, ']' ) !== false ) {

	?><div class="front_page_section front_page_section_title front_page_section_slider front_page_section_title_slider
		<?php
		if ( printo_get_theme_option( 'front_page_title_stack' ) ) {
			echo ' sc_stack_section_on';
		}
		?>
	">
	<?php
		// Add anchor
		$printo_anchor_icon = printo_get_theme_option( 'front_page_title_anchor_icon' );
		$printo_anchor_text = printo_get_theme_option( 'front_page_title_anchor_text' );
	if ( ( ! empty( $printo_anchor_icon ) || ! empty( $printo_anchor_text ) ) && shortcode_exists( 'trx_sc_anchor' ) ) {
		echo do_shortcode(
			'[trx_sc_anchor id="front_page_section_title"'
									. ( ! empty( $printo_anchor_icon ) ? ' icon="' . esc_attr( $printo_anchor_icon ) . '"' : '' )
									. ( ! empty( $printo_anchor_text ) ? ' title="' . esc_attr( $printo_anchor_text ) . '"' : '' )
									. ']'
		);
	}
		// Show slider (or any other content, generated by shortcode)
		echo do_shortcode( $printo_slider_sc );
	?>
	</div>
	<?php

} else {

	?>
	<div class="front_page_section front_page_section_title
		<?php
		$printo_scheme = printo_get_theme_option( 'front_page_title_scheme' );
		if ( ! empty( $printo_scheme ) && ! printo_is_inherit( $printo_scheme ) ) {
			echo ' scheme_' . esc_attr( $printo_scheme );
		}
		echo ' front_page_section_paddings_' . esc_attr( printo_get_theme_option( 'front_page_title_paddings' ) );
		if ( printo_get_theme_option( 'front_page_title_stack' ) ) {
			echo ' sc_stack_section_on';
		}
		?>
		"
		<?php
		$printo_css      = '';
		$printo_bg_image = printo_get_theme_option( 'front_page_title_bg_image' );
		if ( ! empty( $printo_bg_image ) ) {
			$printo_css .= 'background-image: url(' . esc_url( printo_get_attachment_url( $printo_bg_image ) ) . ');';
		}
		if ( ! empty( $printo_css ) ) {
			echo ' style="' . esc_attr( $printo_css ) . '"';
		}
		?>
	>
	<?php
		// Add anchor
		$printo_anchor_icon = printo_get_theme_option( 'front_page_title_anchor_icon' );
		$printo_anchor_text = printo_get_theme_option( 'front_page_title_anchor_text' );
	if ( ( ! empty( $printo_anchor_icon ) || ! empty( $printo_anchor_text ) ) && shortcode_exists( 'trx_sc_anchor' ) ) {
		echo do_shortcode(
			'[trx_sc_anchor id="front_page_section_title"'
									. ( ! empty( $printo_anchor_icon ) ? ' icon="' . esc_attr( $printo_anchor_icon ) . '"' : '' )
									. ( ! empty( $printo_anchor_text ) ? ' title="' . esc_attr( $printo_anchor_text ) . '"' : '' )
									. ']'
		);
	}
	?>
		<div class="front_page_section_inner front_page_section_title_inner
		<?php
		if ( printo_get_theme_option( 'front_page_title_fullheight' ) ) {
			echo ' printo-full-height sc_layouts_flex sc_layouts_columns_middle';
		}
		?>
			"
			<?php
			$printo_css      = '';
			$printo_bg_mask  = printo_get_theme_option( 'front_page_title_bg_mask' );
			$printo_bg_color_type = printo_get_theme_option( 'front_page_title_bg_color_type' );
			if ( 'custom' == $printo_bg_color_type ) {
				$printo_bg_color = printo_get_theme_option( 'front_page_title_bg_color' );
			} elseif ( 'scheme_bg_color' == $printo_bg_color_type ) {
				$printo_bg_color = printo_get_scheme_color( 'bg_color', $printo_scheme );
			} else {
				$printo_bg_color = '';
			}
			if ( ! empty( $printo_bg_color ) && $printo_bg_mask > 0 ) {
				$printo_css .= 'background-color: ' . esc_attr(
					1 == $printo_bg_mask ? $printo_bg_color : printo_hex2rgba( $printo_bg_color, $printo_bg_mask )
				) . ';';
			}
			if ( ! empty( $printo_css ) ) {
				echo ' style="' . esc_attr( $printo_css ) . '"';
			}
			?>
		>
			<div class="front_page_section_content_wrap front_page_section_title_content_wrap content_wrap">
				<?php
				// Caption
				$printo_caption = printo_get_theme_option( 'front_page_title_caption' );
				if ( ! empty( $printo_caption ) || ( current_user_can( 'edit_theme_options' ) && is_customize_preview() ) ) {
					?>
					<h1 class="front_page_section_caption front_page_section_title_caption front_page_block_<?php echo ! empty( $printo_caption ) ? 'filled' : 'empty'; ?>"><?php echo wp_kses( $printo_caption, 'printo_kses_content' ); ?></h1>
					<?php
				}

				// Description (text)
				$printo_description = printo_get_theme_option( 'front_page_title_description' );
				if ( ! empty( $printo_description ) || ( current_user_can( 'edit_theme_options' ) && is_customize_preview() ) ) {
					?>
					<div class="front_page_section_description front_page_section_title_description front_page_block_<?php echo ! empty( $printo_description ) ? 'filled' : 'empty'; ?>"><?php echo wp_kses( wpautop( $printo_description ), 'printo_kses_content' ); ?></div>
					<?php
				}

				// Buttons
				if ( printo_get_theme_option( 'front_page_title_button1_link' ) != '' || printo_get_theme_option( 'front_page_title_button2_link' ) != '' ) {
					?>
					<div class="front_page_section_buttons front_page_section_title_buttons">
					<?php
						printo_show_layout( printo_customizer_partial_refresh_front_page_title_button1_link() );
						printo_show_layout( printo_customizer_partial_refresh_front_page_title_button2_link() );
					?>
					</div>
					<?php
				}
				?>
			</div>
		</div>
	</div>
	<?php
}
